[package]
name = "normdecimal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_decimal = "1"
serde = { version = "1.0.136", features = ["derive"] }
