[package]
name = "normdecimal"
description = "Always normal decimal numbers"
version = "0.1.0"
authors = ["Konstantin Stepanov <me@kstep.me>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_decimal = "1"
serde = { version = "1", features = ["derive"] }
