[package]
name = "normdecimal"
description = "Always normal decimal numbers"
version = "0.1.1"
authors = ["Konstantin Stepanov <me@kstep.me>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
borsh = ["rust_decimal/borsh", "dep:borsh"]

[dependencies]
rust_decimal = "1"
serde = { version = "1", features = ["derive"] }
borsh = { version = "0.9", optional = true }